---
name: yesod-auth-oauth2
version: '0.6.1.4'  # N.B. PVP-compliant Semver: 0.MAJOR.MINOR.PATCH
synopsis: OAuth 2.0 authentication plugins
description: Library to authenticate with OAuth 2.0 for Yesod web applications.
category: Web
author: Tom Streller
maintainer: Pat Brisbin <pbrisbin@gmail.com>
license: MIT
github: thoughtbot/yesod-auth-oauth2
homepage: http://github.com/thoughtbot/yesod-auth-oauth2

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base >=4.9.0.0 && <5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - errors
    - hoauth2
    - http-client
    - http-conduit
    - http-types
    - microlens
    - mtl
    - random
    - safe-exceptions
    - text
    - uri-bytestring
    - yesod-auth
    - yesod-core

executables:
  yesod-auth-oauth2-example:
    main: Main.hs
    source-dirs: example
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - yesod-auth-oauth2
      - aeson
      - aeson-pretty
      - bytestring
      - containers
      - http-conduit
      - load-env
      - text
      - warp
      - yesod
      - yesod-auth
    when:
      - condition: ! '!(flag(example))'
        buildable: false

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - yesod-auth-oauth2
      - hspec
      - uri-bytestring

flags:
  example:
    description: Build the example application
    manual: false
    default: false
